<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>a52ff648-5a5c-410e-9dcc-77a35555a831</elementGuidId>
    <imagePath></imagePath>
    <name>hyperlink_video_tutorials</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/nav[1]/div[1]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>CSS</key>
            <value>[href='\/video-tutorials']</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@class,'navbar__item navbar__link')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <tag></tag>
    <useRalativeImagePath>False</useRalativeImagePath>
    <webElementProperties>
        <isSelected>True</isSelected>
        <matchCondition>equals</matchCondition>
        <name>class</name>
        <type>Main</type>
        <value>navbar__item navbar__link</value>
        <webElementGuid>09118a61-0588-4b56-b118-6b6b8632ef4f</webElementGuid>
    </webElementProperties>
</WebElementEntity>